AWSTemplateFormatVersion: 2010-09-09
Description: root stack
Parameters:
  ENV:
    AllowedValues:
    - dev
    - prod
    Default: dev
    Type: String
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf1554356/88ec60a4b14016b4024aae19633dcdc4.template
  sg:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf1554356/ac3c3ce28c044a8adbd3f1610c39b668.template
      Parameters:
        VpcId:
          Fn::GetAtt:
          - vpc
          - Outputs.vpcId
  instance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf1554356/346a982619de81ddcd8dee96c14c30f3.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - vpc
          - Outputs.subnetId
        SecurityGroupId:
          Fn::GetAtt:
          - sg
          - Outputs.sgId
        ENV:
          Ref: ENV
