AWSTemplateFormatVersion: 2010-09-09
Description: root stack
Parameters:
  ENV:
    AllowedValues: [dev, prod]
    Default: dev
    Type: String
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
  sg:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sg.yaml
      Parameters:
        VpcId: !GetAtt vpc.Outputs.vpcId
  instance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: instance.yaml
      Parameters:
        SubnetId: !GetAtt vpc.Outputs.subnetId
        SecurityGroupId: !GetAtt sg.Outputs.sgId
        ENV: !Ref ENV